### ISSUE TITLE
win7 64bit：mip add 'Error 存在同名页面！'

### ISSUE THREAD

**Issue by Italia458** [mipengine/mip#117]
跟官博跑了一下mip的组件环境，执行到：
`mip add index.html`
`mip add index.html mip-share`

提示：
`ERROR 存在同名页面！`

mip add index2.html 也是一样的。问下原因？

-----------------------已解决，文档太主观---------------------

**Comment by wupengFEX** [comment]
官博文章[MIP开发教程(二) 使用MIP-CLI工具调试MIP网页](http://www.cnblogs.com/mipengine/p/mip_cli_2_page.html)有说明；

`mip add pageName [JSModule]`命令在使用时`pageName`代码需要生成的页面名称，`JSModule`表示需要引入的组件js脚本。

**Comment by Italia458** [comment]
文档应写成：`mip add index.html` 创建一个静态页；或者`mip add index.html mip-alert`，实质是在index.html创建后不能插入组件，只在在创建新页面时可插入。

**Comment by wupengFEX** [comment]
@Italia458 因为页面生成的前提是会检测当前文件夹下是否存在该文件，如果存在则不重复生成，如果期望强制覆盖，可以通过在后面加上`-f`参数，这样产出的文件是你所需要的，你也可以通过`mip add -h`查看其中所有涉及到的命令。
