### ISSUE TITLE
mip.js放在head中，页面会报错并显示空白

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip#152]
## 问题分类
（请在括号中输入"x"来选择）
- [ x ] MIP 页面内容（广告不显示，排版错乱）

## 问题描述
mip.js放在head中，页面会报错并显示空白

**Comment by momofan** [comment]
@pearlwang1106  校验升级需求

**Comment by momofan** [comment]
已提测

**Comment by momofan** [comment]
已上线
