### ISSUE TITLE
mip-pix 不會替換非指定名稱變數之內容

### ISSUE THREAD

**Issue by irvin** [mipengine/mip#155]
由於 https://github.com/mipengine/mip/commit/4dd80cc3ae4bf5bbfa88a959d201dc92acef8d43#diff-9776594e8835a6366f9e3b834557b78cR16 的實作方式，
目前 mip-pix 只會替換變數名稱為「title, host, t」的變數內容，
任何其他追蹤服務，只要其變數名稱非 t / host / title，就無法適用。

例如以下寫法（變數名稱為 pt, ptitle, phost）替換變數即無效：
`<mip-pix src="https://www.mipengine.org/a.gif?pt={t}&ptitle={title}&phost={host}&area=A"></mip-pix>`

建議修改行為：應檢測 `{變數名稱}`（例如 `{t}, {title}, {host}`），並將之替代為對應變數。

測試資料 1
`<mip-pix src="https://www.mipengine.org/a.gif?t_x={t}&title_x={title}&host_x={host}&area=A"></mip-pix>`
預期結果 1
`<mip-pix src="https://www.mipengine.org/a.gif?t_x=__時間__&title_x=__頁面標題__&host_x=__頁面網址__&area=A"></mip-pix>`

測試資料 2
`<mip-pix src="https://www.mipengine.org/a.gif?t={t}&title={title}&host={host}&area=A"></mip-pix>`
預期結果 2
`<mip-pix src="https://www.mipengine.org/a.gif?t=__時間__&title= __頁面標題__&host=__頁面網址__&area=A"></mip-pix>`

另外也建議改用 `${變數名稱}`，以符合 JS Template Literals 的語法習慣。

**Comment by wupengFEX** [comment]
@jennyliang220 看一下是规范约定还是做一下优化

**Comment by jennyliang220** [comment]
1. 变量名确实不需要限制为t, title, host，有必要修改

**Comment by jennyliang220** [comment]
# mip-pix 升级方案
以`<mip-pix src="https://www.mipengine.org/a.gif?t={TIME}&title={TITLE}&host={HOST}&address={ADDRESS}&area=A"></mip-pix>`为例：

## 1. 支持url中key可配置
以{TIME}, {TITLE},{HOST}为key，做查找替换，插入对应的时间，标题和当前页url。前面的t，title，host以站长写的为准。也就是说，支持t={TIME}以及time={TIME}情况，但不支持t={TIME001}这种情况
## 2. 增加大小写支持
支持t={TIME}以及t={time}情况。
## 3. 增加匹配失败的默认操作
如示例中`&address={ADDRESS}&`, {ADDRESS}匹配失败。最终发请求的时候，替换为`&address=&`。保证由MIP-PIX定义的语法'{', '}'不在最终请求中出现。

**Comment by irvin** [comment]
針對這三個需求，在 PR #156 都補完了，請檢查。

**Comment by jennyliang220** [comment]
下午组内讨论，结论已经更新到方案中。与上个版本的方案相比，需求2有修改，删除了需求3，新增`${xxx}`兼容方案

**Comment by irvin** [comment]
根據最新需求修改了 PR
