### ISSUE TITLE
mip-pix 文檔中關於 referrer 說明需更新以符合新的網頁規範

### ISSUE THREAD

**Issue by irvin** [mipengine/mip#158]
https://www.mipengine.org/examples/mip/mip-pix.html
> 添加referrer
> 在html <head> 标签中增加<meta name="referrer" content="always">, 可以在请求头中增加referrer信息

上述段落中的說明須更新，新的規範中，相對應的參數是 `content="unsafe-url"`
https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-unsafe-url

**Comment by momofan** [comment]
@irvin 很高兴看到你提出的 w3c 规范变更的建议，https://html.spec.whatwg.org/multipage/semantics.html#meta-referrer  我们也看到了 的确是新老的版本更新，这个着手进行更新

**Comment by jennyliang220** [comment]
已上线。
