### ISSUE TITLE
mip-form 组件内嵌套 mip-img组件 ，每次插入dom的时候都会执行一遍 layout.js

### ISSUE THREAD

**Issue by GKrace** [mipengine/mip#160]
## 问题分类
线上bug

## 问题描述
mip-form 组件内嵌套 mip-img组件 ，每次插入dom的时候都会执行一遍 layout.js
## 复现方式（线上bug 填写此项）

稳定复现：示例demo：https://gkrace.github.io/test_component/mip-img/online.html

## 修复
修复后demo：https://gkrace.github.io/test_component/mip-img/repair.html

**Comment by momofan** [comment]
已解决上线
