### ISSUE TITLE
Difference between MIP and AMP / MIP和AMP之间的区别

### ISSUE THREAD

**Issue by niutech** [mipengine/mip#165]
What is the difference between MIP and AMP from the developer's perspective? How to make a MIP page from an AMP page and vice versa?

从开发者的角度来看，MIP和AMP有什么区别？ 如何从AMP页面制作MIP页面，反之亦然？

**Comment by wupengFEX** [comment]
这个问题在官方博客的以下两篇文章中均有提及：
- [MIP 与 AMP 合作进展（3月7日）](http://www.cnblogs.com/mipengine/p/20_cooperation_progress.html)
- [MIP 技术交流分享（3月15日）](http://www.cnblogs.com/mipengine/p/22_technology_sharing.html)

另外 AMP 与 MIP 之间的融合官方也在进行中，最新信息请关注[官方网站](https://www.mipengine.org/)和[官方博客](http://www.cnblogs.com/mipengine/)！
