### ISSUE TITLE
mip-img 内置组件功能升级

### ISSUE THREAD

**Issue by momofan** [mipengine/mip#169]
## 问题分类
- [x ] MIP 组件使用

## 问题描述
1、该组件在图片加载之前，占位的地方页面是空白的，可以添加默认图片（是否用户可配？）
2、支持 srcset
3、支持 alt 和 title 属性的值传递
4、图片加载失败能够给一张默认图片（是否用户可配？）

**Comment by jennyliang220** [comment]
5、在不使用layout时，默认增加一个16：9的占位符。减少图片加载产生的抖动

**Comment by jennyliang220** [comment]
1. 5. 图片占位符默认样式：https://jennyliang220.github.io/mip/mip-img/img-loading.html

**Comment by jennyliang220** [comment]
# 改版方案（未完成）
1. `<mip-img>`支持默认占位图片，pearl 在[mip-img.less 的一次修改](https://github.com/mipengine/mip/blame/master/src/less/mip-img.less) 中增加的，但是没有文档。

**Comment by jennyliang220** [comment]
## 预加载
1. 提前一个屏加载图片

## 占位符
1. SF下：cache预先传图片宽高，占位符给出稳定宽高
2. MIP下：获得图片宽高平均比例，确认MIP下占位符宽高

## loading图 + 图片加载失败 图片

**Comment by jennyliang220** [comment]
备用方法：对于非cache页面，或cache未命中缓存页面，根据图片格式（gif, png, jpg）设置img-ratio（宽高比）。默认宽高由mip-cache给出，由10w张相同格式图片的平均宽高比产出。 TODO

**Comment by zhao-ping** [comment]
关于图片的宽高比，并不是所有的图片的宽高比都是一样的，在移动设备上，图片大都是宽度百分百，高度自适应的。关于宽高比这个设计不合理。
文章页面如果有一组的图片的话，而且图片之间没有其他内容，图片每张相连的时候，如果想要实现宽度100%；高度自适应的话，就不能给宽高比这个属性。
但是如果不给宽高比的属性，图片在没有被加载进来时的高度是0，所以会在一开始就加载了所有的图片。

个人建议给个图片min-height的属性，来避免这一问题

**Comment by zhao-ping** [comment]
关于图片的宽高比，并不是所有的图片的宽高比都是一样的，在移动设备上，图片大都是宽度百分百，高度自适应的。关于宽高比这个设计不合理。

文章页面如果有一组的图片的话，而且图片之间没有其他内容，图片每张相连的时候，如果想要实现宽度100%；高度自适应的话，就不能给宽高比这个属性。

但是如果不给宽高比的属性，图片在没有被加载进来时的高度是0，所以会在一开始就加载了所有的图片。

个人建议给个图片min-height的属性，来避免这一问题

**Comment by zhao-ping** [comment]
关于图片的宽高比，并不是所有的图片的宽高比都是一样的，在移动设备上，图片大都是宽度百分百，高度自适应的。关于宽高比这个设计不合理。

文章页面如果有一组的图片的话，而且图片之间没有其他内容，图片每张相连的时候，如果想要实现宽度100%；高度自适应的话，就不能给宽高比这个属性，否则图片可能会被拉伸或者压缩变形。

但是如果不给宽高比的属性，图片在没有被加载进来时的高度是0，所以会在一开始就加载了所有的图片。

建议每次最多加载5张图片（或者给个参数，用户可自定义每次加载的图片的数量），图片加载完毕后再重新计算剩下的图片。

**Comment by jennyliang220** [comment]
@zhao-ping 感谢建议。解释一下你提的问题：
1. 宽高是placeholde的属性，与图片本身高度无关，不会造成图片拉伸变形问题。可以看下这个demo。chrome调整网络速度可以看到效果：https://jennyliang220.github.io/blog/img-loading/demo6.html
2. 加载5张（或可配置）不太实际。站长要么忽略这个功能，要么为了省事直接设置成100. 最好还是按需加载。

**Comment by jennyliang220** [comment]
从服务端跑了一些数据，为了获取图片的最常见尺寸。比例如下：
比例|gif|png|jpg
----|----|----|----
3:1|22.44%
2:1|9.35%
3:4 | 6.31%



4:3|16.29%
9:16|5.48%
1:1|23.64%

**Comment by jennyliang220** [comment]
测试页面：

**Comment by jennyliang220** [comment]
测试页面：
1. https://jennyliang220.github.io/mip/mip-img/demo.html
2. https://jennyliang220.github.io/mip/mip-img/douguo.html

**Comment by momofan** [comment]
测试中
