### ISSUE TITLE
mip-zpm-jobdetail组件提交后，审核通不过

### ISSUE THREAD

**Issue by wangjx90** [mipengine/mip#170]
mip-zpm-jobdetail组件审核结果如下
由于组件使用了特殊【登录】和【cookie】功能，请到github 提交 issue， 详细描述您的功能和需求: https://github.com/mipengine/mip-extensions/issues 我们会有技术同学专门解答您的问题 
请帮忙处理

**Comment by jennyliang220** [comment]
组件issue请提到 https://github.com/mipengine/mip-extensions
