### ISSUE TITLE
MIP.CSS里关于mip-carousel 的mip-carousle-subtitle  建议加半透明背景

### ISSUE THREAD

**Issue by Edims** [mipengine/mip#181]
> .mip-carousle-subtitle {
> ....code;
> background-color: rgba(0, 0, 0, 0.43);
> }
> 

![11](https://user-images.githubusercontent.com/25048319/28450586-b54daf36-6e1a-11e7-9d77-1b30d6e81503.png)
没有背景图，文字无法看清楚
![22](https://user-images.githubusercontent.com/25048319/28450592-c1c9d8ac-6e1a-11e7-9e54-d024a0813bdf.png)
加上半透明背景后，文字更好辨识，也算是用户体验吧

**Comment by Edims** [comment]
没人答复一下？

**Comment by wupengFEX** [comment]
感谢提交issue，这个问题你可以自行在`<style mip-custom></style>`中设置需要的样式进行重载。

**Comment by Edims** [comment]
既然这样回答，那我就自己动手了，不等你们来搞了
