### ISSUE TITLE
MIP-PIX 增加 referrer 参数

### ISSUE THREAD

**Issue by irvin** [mipengine/mip#194]
目前的 mip-pix 没有支援将 referrer header 的内容带到分析服务后台，且 MIP 流量不会经由服务伺服器，因此无法分析流量来源来自于哪些搜索引擎或网站。

建议增加一参数（如 {referer}），并自动带入 encodeURIComponent(document.referrer) 内容

**Comment by wupengFEX** [comment]
复杂的统计需求建议使用统计组件，如 [mip-stats-baidu](https://www.mipengine.org/examples/mip-extensions/mip-stats-baidu.html)，[mip-analytics](https://www.mipengine.org/examples/mip-extensions/mip-analytics.html)。
