### ISSUE TITLE
图片预加载建议改成提前一屏加载，而不是进入屏幕时加载。

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip#195]
图片默认占位符解决不了图片闪现的问题，真实图片请求还是由firstInviewCallback触发的。而图片闪现，本身对用户的感知就是网速好慢，图片刚刚才加载出来。和MIP速度快其实是不一致的。

能不能加上默认展现的图片高度是**两屏**，这样用户在正常浏览的时候，基本看不到图片的抖动了。 除非用户猛划页面向下滚动，但是这个情况，是用户非正常浏览的情况。

**Comment by momofan** [comment]
MIP 机制是按需加载资源，图片的加载体验使用 layout 来实现，提前加载一屏固然能让图片提前加载，但是无形还是要增加额外一屏的用户的图片带宽。此方案暂不实施

**Comment by tayqassqan** [comment]
近期我们重新review了此问题，提前加载对体验更加友好，让用户的预期更加稳定，我们需要尽快优化此功能。
