### ISSUE TITLE
是否是一个mip页面

### ISSUE THREAD

**Issue by 520huihuizhou** [mipengine/mip#201]
一个页面怎么正确的判定它是不是mip页面，求解

**Comment by wupengFEX** [comment]
- 如果页面已上线，可以在搜索结果下方看是否有一个蓝色闪电标，如果有则是；

![image](https://user-images.githubusercontent.com/8186657/30311598-a603405e-97c8-11e7-9dea-e2726d347208.png)

- 如果未上线，想成为一个标准的mip页，需要遵守mip规范进行开发，同时可以将代码放在 [mip校验工具](https://www.mipengine.org/validator/validate)里，检测校验结果。
@520huihuizhou
