### ISSUE TITLE
你好，请教mip缓存更新机制

### ISSUE THREAD

**Issue by zituocn** [mipengine/mip#204]
你好：

我的移动站已经上线，全部使用mip开发，地址是：https://m.cz89.com
通过站长平台后台的移动匹配，现在已有部分页面生效(mip)。

目前发现一个较严重的问题，希望能解决或回复，如无更好的解决办法，只有放弃mip的使用。

1、mip对页面进行了缓存，而且时间较长，比如列表页，能否对这个时间可配置？
2、网站上有部分时效性较高的内容，比如彩票的开奖号码，如果使用mip cache api来清理缓存，需要请求的页面也很多，100s内不超过10次的限制，很逆天。
3、能否提供像其他公司cdn的配置后台，比如设置哪一类页面的过期时间(通过正则)。
4、如果没有配置后台，或者通过response header方式，来实现第3点的控制？

总之，对内容的时效性，mip处理的太欠佳了！

期望回复，谢谢！

**Comment by jennyliang220** [comment]
页面部分内容频繁更新的情况，更适合封装js组件，异步从服务器获取数据并更新。
对应的技术方案见 Issue #376，MIP项目组会在第四季度支持这个需求。

**Comment by cg82616424** [comment]
内容频繁 这个应该是实时更新吧~~

**Comment by zituocn** [comment]
感谢回复。
这是实时更新的数据，持续关注 mip-live-list
