### ISSUE TITLE
建议官方文档开源

### ISSUE THREAD

**Issue by yugasun** [mipengine/mip#213]
昨天修改 `mip-img` 图片的时候，因为我已图片是 `position:absolute`，然而 `mip-img` 默认会有个标签包裹 `img` 标签，所以整体定位依赖父级标签 `mip-img`，然而它默认是 `position:relative` 试了半天，才发现我的图片如果想绝对定位，`layout` 必须为 `fill`....，此时 `mip-img` 才是绝对定位。

鉴于踩过的坑，所以希望能够更新官方文档，方便后来者不再踩坑。

**Comment by xuexb** [comment]
hi @yugasun ，官网文档已开源至 [mipengine/www.mipengine.org](https://github.com/mipengine/www.mipengine.org) 仓库，可点击 [MIP 官网贡献指南](https://github.com/mipengine/www.mipengine.org/blob/master/CONTRIBUTING.md) 查看更多帮助。
