### ISSUE TITLE
Does MIP-Cache supports Google AMP?

### ISSUE THREAD

**Issue by taytus** [mipengine/mip#216]
Hello!

I know AMP-Cache does not work in mainland China, but I know Baidu is indexing AMP pages. Does MIP-Cache caches AMP pages?

Thank you.

**Comment by jennyliang220** [comment]
Hi, Taytus
Baidu-Cache is ready for AMP pages, but AMP page recognition and validation is still under development. AMP pages will be recognized and shown by Baidu Search in late October.

AMP pages shown in Baidu search will have the same acceleration effect as MIP, so there is no need to build additional MIP pages.

**Comment by yugasun** [comment]
If so, in the future we can just dev either MIP or AMP pages for the same cache?
