### ISSUE TITLE
MIP 页面事件 event-action 讨论

### ISSUE THREAD

**Issue by xuexb** [mipengine/mip#228]
遵循 MIP 规范，页面元素使用 event-action 形式，如： `<div on="tap:test.custom_event">不带参数</div>` （[文档](https://www.mipengine.org/doc/3-widget/6-help/3-mip-normal.html)），但由于是 `tap` 事件，如果应用于一些事件里会覆盖触发元素的场景（如：弹出层），就会发生点击穿透，场景如：

在页面中 `<button on="tap:right-sidebar.open">` 点击按钮时让一个 sidebar 显示，而这个 sidebar 是个弹层，弹层中又有一些跳转链接，导致点击时先触发弹层显示，又直接跳转了页面。

本身想使用 `on="click:right-sidebar.open"` 解决，但没有该接口。而 `tap` 事件在 pc 中又是由 `click` 替换，从而在 pc 中又复现不了。

via:

<https://github.com/mipengine/mip/blob/8426f656206de3dfba3ff955146dd2ee74ea4098/src/viewer.js#L122-L136>

**Comment by xuexb** [comment]
> 从而在 pc 中又复现不了

额，发现在 pc 使用模拟器还是可以复现的。因为模拟器里有 `touch` 相关事件。

**Comment by jennyliang220** [comment]
复议，我也遇到类似问题。

## 使用场景：
将弹层（mip-lightbox）组件与mip-form表单共同使用，接收用户输入。当mip-form提交时获取输入内容，触发弹层显示，将内容显示在弹层中。

## 遇到的问题
我写了个性化组件来读取用户输入，显示在弹层中。但在个性化组件中不能获取弹层对应的customElement，也就不能触发弹层内部暴露出来的[open事件](https://github.com/mipengine/mip-extensions/blob/master/src/mip-lightbox/mip-lightbox.js#L41)。

## 建议
将customElement和对应DOM绑定，通过DOM能获取customElement 属性及公共方法。提供触发组件公共方法的函数，如MIP.trigger(querySelector('#lightbox'), 'open')。

**Comment by xuexb** [comment]
并且梳理下现在使用的事件，比如：

- tap
- click
- swipe
- change

**Comment by xuexb** [comment]
还有，事件这块能不能实现一些通用的方法，如：跳转链接 `on="eventName.jumpurl:https://xuexb.com/?word=event.target.value"` ，这将提升一些事件的易用性。

**Comment by xuexb** [comment]
关联 https://github.com/mipengine/mip-extensions/issues/986 ，也需要考虑

**Comment by xuexb** [comment]
AMP 这块做的相当完善：<https://www.ampproject.org/docs/interaction_dynamic/amp-actions-and-events>

**Comment by xuexb** [comment]
#288

**Comment by xuexb** [comment]
```js
/**
 * @file 尚医健康添加广告关闭按钮
 * @author sytown
 * @version 1.0.0
 */
define(function (require) {
    var customElement = require('customElement').create();
    var util = require('util');

    /**
     * build
     *
     */
    function build() {

        var that = this;

        that.addEventAction('close', function (event) {
            event.preventDefault();
            util.css(that.element, 'display', 'none');
        });
    }

    customElement.prototype.build = build;

    return customElement;
});

```

**Comment by xuexb** [comment]
添加了 `on="click:id.action"` 事件，<https://github.com/mipengine/mip/issues/307>
