### ISSUE TITLE
mip-nav-slidedown 菜单在iPad上表现异常

### ISSUE THREAD

**Issue by gobyway** [mipengine/mip#234]
## # 图1是mip-nav-slidedown菜单在iPhone5 Safari上的表现（表现正常）
![iphone](https://user-images.githubusercontent.com/19703198/32710020-f35cfb42-c86f-11e7-8c67-b04176de7884.jpg)
## # 图2是mip-nav-slidedown菜单在iPad mini4 Safari上的表现（表现异常：data-brandname文字与nav的各个子项发生重叠，如红框中所示）
![ipad mini4](https://user-images.githubusercontent.com/19703198/32710126-cb892b44-c870-11e7-96b9-6fef604065e5.png)

联系方式：156-0431-2041

**Comment by jennyliang220** [comment]
由于导航链接过多，从右向左排列元素就覆盖到了标题。建议合并链接内容。使用mip-nav-slidedown的【增加二级菜单】功能。
![272b4c7b8e88b05bc9f21b42cf33483d](https://user-images.githubusercontent.com/8498677/32766995-1af89d8e-c8d7-11e7-83bf-01a663886681.png)

**Comment by gobyway** [comment]
好的，谢谢你，明白了
