### ISSUE TITLE
util.platform未提供判断PC/H5 UA的功能

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip#235]
util.platform文档：https://www.mipengine.org/doc/3-widget/6-help/1-introduce.html
需求：根据平台不同，绑定click/touchend事件。

**Comment by xuexb** [comment]
其实我理解统一绑定 click 不是很好吗？现在的浏览器日益增强，对 click 300ms 延迟已经有很多优化了。
使用 touch 相关事件很容易造成事件穿透问题。

并且我认为应该添加个 `<div on="click:xx">` 而不是用 `on="tap:xx"` 事件处理在 PC 是点击，在移动端是 tap 。
