### ISSUE TITLE
position:fixed元素在iframe下直接移除，是否不太友好

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip#236]
![image](https://user-images.githubusercontent.com/8498677/32766716-c3c48b5a-c8d5-11e7-82d4-902ff9e89516.png)
页面存在position: fixed样式，导致在iframe下触发MIP的兼容逻辑。具体为找到所有声明为fixed元素并移除，代码见：https://github.com/mipengine/mip/blob/51dbededbe1b54b4f8f32d437ffe99f2e19004fc/src/fixed-element.js#L252。

直接移除操作会导致页面元素丢失，严重会导致页面白屏。建议换用mip-fixed逻辑，移动目标元素，而不是直接移除。
![image-20171114142704-zgddnz](https://user-images.githubusercontent.com/8498677/32766807-1efd743c-c8d6-11e7-879b-6baa7e282ada.png)

**Comment by xuexb** [comment]
本周我写了各种 case 的页面，并在非 iframe 和 iframe 下进行测试回归，并给如何优化 fixed 相关的逻辑~

**Comment by xuexb** [comment]
插入到 body 外+无动画 css 是为了解决 ios 端滑动 fixed 元素跑偏问题。

1. 目前是只有线上（ iframe 内 ）才会移动元素，导致开发和生产有 diff ，需打平。
1. 目前是只判断只要是 fixed 就移动，应该考虑复杂的选择器不移动元素，只在控制台警告用户这个元素可以优化下之类的文案。
1. 尝试生成 body 同级的元素，但不叫 body ，可以叫个 `div class="fixed-player"` 之类的。
1. 目前处理 fixed 元素和组件代码相当的耦合，应该组件是组件，处理 fixed 逻辑的功能要剥离。

测试示例链接：

- [iframe 内测试链接](https://static.xuexb.com/fixed/iframe.html)
- [测试使用各种 case 原链接](https://static.xuexb.com/fixed)

**Comment by xuexb** [comment]
目前已经制定初步方案：

1. 站长自定义的 `position: fixed` 元素不移除，提示升级为组件更佳
1. 打开环境，在开发环境时就可以发现问题
1. 把 mip-fixed mip-semi 和核心代码解耦

我们内部再评审下具体方案实施，我再详情同步。

目标就是：

1. 默认 fixed 使用不影响，使用优化后更佳
2. 让问题暴露在开发环境，从而提升开发体验
