### ISSUE TITLE
关于 build 和 firstInviewCallback 拿不到组件内DOM报错的问题

### ISSUE THREAD

**Issue by vivine** [mipengine/mip#249]
起因：
页面缓存到 mip cdn 上后，会把所有引用组件的 script 标签放到 `head` 里边，并加上 async 。这个跟mip 规范上说的不太一致，规范上说开发的时候 script 标签要放在页面底部 `</body>` 的前面。

结果：
访问 mip cdn 上的页面，如果组件里边需要有 DOM 或者说通过 `<script type="application/json"></script>` 来传数据，不管是用 build 还是 firstInviewCallback 都会导致相同的问题，那就是 `this.element.querySelector()` 获取不到DOM节点，导致报错。

猜测：
1、build 的发生时间应该是在这个自定义组件标签，比如 `mip-xxx` ，它本身插入到DOM里边的时候，这个时候，自定义标签里边的其他DOM还没生成，所以拿不到，故而报错。
2、firstInviewCallback 应该是当自定义标签进入视口的时候触发，如果这个时候已经build完成，应该是能拿到自定义组件标签里边的DOM的。但是有特殊情况，比如说浏览器记录用户页面位置（用户刷新页面还是会滚到到上次访问的位置），或者这个自定义组件一打开页面就在视口范围内，firstInviewCallback 会跟 build 几乎在同一时间执行，而此时自定义组件标签里边的 DOM 还没插入。所以拿不到，故而报错。

当然，如果把 js 引用都放在页面底部，则不会出现上面所说的问题。也可能跟页面打开速度和页面的大小有关系，如果页面里边东西很少，非常快速就能渲染DOM的话，即使 js 放在页面head里边也应该不会出现上述问题。

![](http://up.fd.zol-img.com.cn/g5/M00/01/02/ChMkJ1orlx2IB4SYAADw-_iiHnsAAi_YwDjsnkAAPET959.jpg)

请mip官方给与解答，谢谢！

**Comment by wupengFEX** [comment]
@vivine 感谢反馈，该问题已解决！
