### ISSUE TITLE
文档需要统一维护

### ISSUE THREAD

**Issue by harttle** [mipengine/mip#25]
MIP核心代码的文档（教程和API）文档需要统一维护吧？当前该项目下并没有最新的API文档，现在更新一个文档可能需要手动地同步到官网和内网文档。列一下我知道的文档：
- github:mipengine/mip: src/builtin/*.md
- github:mipengine/mip: docs/
- github:mipengine/mip-extensions: */readme.md
- gitlab: mip/mipengine（貌似官网在用这个里的doc）
- gitlab: mip/mipmain（貌似废弃了？）

以下（活跃的）文档有重合但不同步：
- 官网与src/builtin/*.md
- 官网与mip-extensions: */readme.md

现在superframe是这样维护文档的，看是否可以参考：
1. 源码仓库中维护API注释（文档）
2. 文档仓库中维护教程文档
3. 源码/文档仓库的push都会触发文档仓库更新在线文档

文档更新流程（还未完全实现）：
1. pull最新的文档仓库，获得教程文档
2. pull最新的源码仓库，并生成API文档（superframe是从代码生成API文档的）
3. 更新在线文档。

另，
- 官网文档结构有点confuse：开发指南->让搜索发现你的页面，技术规范->让搜索发现你的页面规范升级
- MIP核心代码缺少API文档？

**Comment by xuexb** [comment]
我个人感觉源码就是源码吧, 如果文档较少可以放一块, 如: `/docs/*`, 但如果较多, 放别一个仓库比较好吧. 

至于你说的api方法文档, 是根据源码自动生成的?(jsdoc)

内外网自动同步不是问题吧.

**Comment by wupengFEX** [comment]
@harttle 核心代码文档机制也在计划中，后续会陆续落地并及时通知！

**Comment by momofan** [comment]
@wupengFEX 尽快给出合理解决方案

**Comment by xuexb** [comment]
文档已开源至 [mipengine/www.mipengine.org](https://github.com/mipengine/www.mipengine.org) 仓库，可点击 [MIP 官网贡献指南](https://github.com/mipengine/www.mipengine.org/blob/master/CONTRIBUTING.md) 查看更多帮助。
