### ISSUE TITLE
关于使用mip-app-banner App 吊起组件问题

### ISSUE THREAD

**Issue by PLDaily** [mipengine/mip#251]
安卓下使用<link rel="manifest" href="https://xxxx/manifest.json">没有反应。
<img width="695" alt="2017-12-13 2 30 30" src="https://user-images.githubusercontent.com/11615211/33924699-358760ca-e012-11e7-8d07-3176c13eadbd.png">
这里的结果页和非结果页是什么意思，是安卓下不支持？
前面写着布局支持
<img width="682" alt="2017-12-13 2 31 52" src="https://user-images.githubusercontent.com/11615211/33924968-3775ffee-e013-11e7-905c-944a15b04b84.png">
后面写的只支持什么鬼
<img width="443" alt="2017-12-13 2 32 14" src="https://user-images.githubusercontent.com/11615211/33924788-8936be14-e012-11e7-8c0f-a664a937ca3f.png">

[文档](https://github.com/mipengine/mip-extensions/issues/282)里写着解析manifest.json里面的app-id
<img width="671" alt="2017-12-13 2 35 49" src="https://user-images.githubusercontent.com/11615211/33924901-f8f6a516-e012-11e7-8b6d-77a9245ad672.png">

但是 manifest.json 给的示例里都没有app-id这个选项。
<img width="699" alt="2017-12-13 2 36 31" src="https://user-images.githubusercontent.com/11615211/33924915-0fac80f0-e013-11e7-80b4-8af3d7531a48.png">

有具体的示例可供参考吗。。

**Comment by PLDaily** [comment]
谷歌手机调试在安卓下什么都不显示
<img width="1085" alt="2017-12-13 2 53 58" src="https://user-images.githubusercontent.com/11615211/33925662-cf4e4c70-e015-11e7-8ddb-28fa006f3cf9.png">
在ios下显示ya样式也错乱了
<img width="1097" alt="2017-12-13 2 54 24" src="https://user-images.githubusercontent.com/11615211/33925668-d9f939be-e015-11e7-95e8-cf7a5228a3b5.png">

我的代码
```
<!DOCTYPE html>
<html mip>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no,minimum-scale=1,maximum-scale=1" />
    <link rel="stylesheet" type="text/css" href="https://mipcache.bdstatic.com/static/v1/mip.css">
    <title>title</title>
    <meta name="apple-itunes-app" content="app-id=452186370, app-argument=baidumap://">
    <link rel="manifest" href="https://oa.52liuda.com/manifest.json">
</head>
<body>
<div id="container">
    <mip-app-banner id="my-app-banner" layout="nodisplay">
        <button open-button>打开app</button>
    </mip-app-banner>
</div>
<script src="https://mipcache.bdstatic.com/static/v1/mip.js"></script>
<script src="https://mipcache.bdstatic.com/static/v1/mip-app-banner/mip-app-banner.js"></script>
</body>
</html>
```

**Comment by wupengFEX** [comment]
@PLDaily 感谢提出问题，问题迁移到[这里](https://github.com/mipengine/mip-extensions/issues/958)，我们会梳理一遍文档和功能，届时对应的问题会在对应issue里同步。
