### ISSUE TITLE
标签'script'的强制性属性'async'缺失

### ISSUE THREAD

**Issue by ginsonwang** [mipengine/mip#252]
![image](https://user-images.githubusercontent.com/22736704/34086340-014c7c88-e3d6-11e7-919d-394c507c2308.png)

希望能在MIP规范文档中说明，放在head中的script都需要加 async 属性

**Comment by baichengzhou** [comment]
呵呵，为什么它要支持async

**Comment by VenyXiong** [comment]
考虑到mip组件的建在，我们建议把mip组件的js引用放在底部哈。
async属性在mip2中得到了支持，学习文档https://www.mipengine.org/v2
