### ISSUE TITLE
[naming convention] examples and extensions/builtins

### ISSUE THREAD

**Issue by harttle** [mipengine/mip#26]
我们的示例文件命名都是 `xxx-mip.html`（如[examples/img-mip](https://github.com/mipengine/mip/blob/master/examples/img-mip.html))，而extension/builtins都是`mip-xxx.html`（如[builtins/mip-img](https://github.com/mipengine/mip/blob/master/src/builtins/mip-img.js)）。一致一下？

我认为把mip前/后缀干掉就可以，mip项目中的示例HTML当然是mip。

**Comment by wupengFEX** [comment]
@harttle 目前组织结构和你所说的有所不同，如果涉及到相关页面我们也会制定统一命名规范！
