### ISSUE TITLE
a tel在uc下不生效

### ISSUE THREAD

**Issue by wupengFEX** [mipengine/mip#261]
问题：sf 下 `<a href="tel:338665">拨打电话</a>` 在 uc 里不生效，即不能弹出拨打电话的弹框
原因：由于a链接在核心代码里做了代理，同时设置了target='_top'导致；
方案：tel 模式下用非 _top；

**Comment by xuexb** [comment]
via: <https://github.com/mipengine/mip/blob/a251a3f404b10c9211293d65fc0fe1205d44fe39/src/viewer.js#L235-L258>

**Comment by Summer05246** [comment]
该bug只在 iphone的uc 有这个bug

**Comment by momofan** [comment]
已上线修复
