### ISSUE TITLE
mip 图片懒加载在pc上执行缓慢 执行了多余的JS

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip#266]
![1515653175](https://user-images.githubusercontent.com/8498677/34811908-552924f8-f6de-11e7-960c-56e2eaab7879.png)

https://github.com/mipengine/mip/blob/d0ae58fa678dd7ba0d9346f2a542654f8ef0df7b/src/viewport.js#L173 截图中，这个函数执行了100+次，有明显延迟。然后才执行懒加载图片的创建和插入工作。

**Comment by xuexb** [comment]
接锅，这是 `scroll` 内节流函数导致的。
