### ISSUE TITLE
在Safari上 mip-img 对webp支持不到位，部分图片无法显示

### ISSUE THREAD

**Issue by JunIce** [mipengine/mip#273]
针对现在Safari浏览器还不支持webp，我觉得mip-img应该增加一个webp属性给用户传入，原来对img属性不变，有webp优先展示webp

**Comment by JunIce** [comment]
我没说清楚，只是在Safari上通过百度访问会有部分无法显示

**Comment by wupengFEX** [comment]
你的需求 picture 就能解决，可以尝试用一下。mip 的 webp 策略是站长不需要关心图片是不是 webp 的，写 png, jpg 都可以，图片服务上会自动转一份，支持webp的浏览器上返回的就优先是webp（不过方案暂时还未上线）

**Comment by JunIce** [comment]
@wupengFEX 好的，多谢

百度云cdn好像是有转换图片的服务的

**Comment by JunIce** [comment]
![wx20180125-104852](https://user-images.githubusercontent.com/20832069/35368299-a640bc54-01bd-11e8-83d8-f710acf70f2d.png)


验证工具提示source标签只能在mip-video内

**Comment by wupengFEX** [comment]
@JunIce source 的校验在本月会升级上线，可以在 mip-video, mip-audio, picture 中使用，可以关注mip群里校验动态！
