### ISSUE TITLE
看完官方文档后，我还是不知道我自己的 js 放哪里？

### ISSUE THREAD

**Issue by baichengzhou** [mipengine/mip#275]
正如你们所说，我把我的 jQuery 去掉，按原生+你们提供的组件，去写，写完放哪里？没看到相关文档，请给个指示！
https://www.mipengine.org/doc/3-widget/6-help/1-introduce.html
这个文档讲述的，我应该写在哪？

**Comment by baichengzhou** [comment]
<script>标签提示不允许！

**Comment by jennyliang220** [comment]
请参考官网文档第一段：https://www.mipengine.org/doc/3-widget/6-help/1-introduce.html

![image](https://user-images.githubusercontent.com/8498677/35444657-2fe3ca82-02ea-11e8-9378-b29c07e4a368.png)

将javascript脚本封装为MIP组件，提交后使用。

**Comment by baichengzhou** [comment]
谢谢回复。自己的组件都能通过吗。
