### ISSUE TITLE
我弄的mip页面检验成功了,有新问题看这里

### ISSUE THREAD

**Issue by qz463390618** [mipengine/mip#281]
mip页面也可以推送到熊掌号里面去,但是现在推送成功后,在里面看见的是没有头部导航了,然后我看了下代码,直接把我的header标签全部去掉了,这是为什么,下面附上熊账号连接https://m.baidu.com/mip/c/m.ququyou.com/mipa/clxsy/42520.html
再下面是正常网页页面内容
http://m.ququyou.com/mipa/clxsy/42565.html
里面会有导航栏,能说下什么问题吗

**Comment by wupengFEX** [comment]
@qz463390618 页面头部使用了 `position: fixed` 的元素，mip 中不允许，需要替换为 `<mip-fixed>`。
