### ISSUE TITLE
MIP页直接打开正常，但通过百度搜索结果打开，排版乱掉

### ISSUE THREAD

**Issue by NamedDavidChan** [mipengine/mip#285]
我们的站点
http://m.kaoshib.com/
百度搜索结果页面
https://m.baidu.com/mip/c/m.kaoshib.com/

正常页面效果
![image](https://user-images.githubusercontent.com/28563583/36838445-224828d2-1d7a-11e8-9493-a77eaad9486f.png)

百度搜索结果效果
![image](https://user-images.githubusercontent.com/28563583/36838391-02ffce9e-1d7a-11e8-83c8-26c27a8f9a99.png)

通过查看代码，发现代码被乱嵌套了一通。。。

**Comment by xuexb** [comment]
我发现你源站的页面中存在：

```
<mip-img alt='2018年银行从业资格考试准考证打印时间' src='http://kaoshib.com/uploads/180208/5-1P20Q12305937.jpg' layout='responsive' width='600' height='400'/></mip-img>
```

结构为 `<mip-img /></mip-img>` ，多了个 `/` 。

**Comment by NamedDavidChan** [comment]
好的，感谢！我再试试！
