### ISSUE TITLE
mip组件，有复制粘贴剪切板组件吗？

### ISSUE THREAD

**Issue by 520huihuizhou** [mipengine/mip#286]
如上，项目有用到剪切板功能，想问一下有没有组件可以使用此功能的，急用，谢谢

**Comment by jennyliang220** [comment]
可以看下组件仓库。mip-extensions 和 mip-extensions-platform

**Comment by 520huihuizhou** [comment]
哪里又组件仓库，没有找到你说的 mip-extensions 和 mip-extensions-platform

**Comment by 520huihuizhou** [comment]
???
