### ISSUE TITLE
app下载组件怎么同时使用多个-downsrc

### ISSUE THREAD

**Issue by 520huihuizhou** [mipengine/mip#287]
app下载组件，这种情况不能用吗，只出来了一个
<mip-appdl class="aaa" tpl="imageText" src="http://192.168.10.99:8020/MIPstoneread/images/ios_download.png"
		texttip= "ios下载" downbtntext="ios" Ios-downsrc="https://itunes.apple.com/cn/app/id978602200">
	</mip-appdl>

	<mip-appdl class="aaa" tpl="noneImg" src="http://192.168.10.99:8020/MIPstoneread/images/ios_download.png"
		texttip= "安卓下载" downbtntext="安卓"
		Android-downsrc="https://stone.mini-install.com/resources/apk/app-release-reader-2.9-57-201802241543_signed_zipalign.apk">
	</mip-appdl>
![2](https://user-images.githubusercontent.com/24927625/37502391-6a35b58a-290d-11e8-837e-cdf0c38ac35f.jpg)

![1](https://user-images.githubusercontent.com/24927625/37502349-4210e02a-290d-11e8-87aa-64a1ef7df6b5.jpg)

**Comment by jennyliang220** [comment]
下载链接只有一个。这个是点击后跳转的链接。
