### ISSUE TITLE
 强大的eventaction 的用法明确，文档细化，demo产出

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip#288]
可以解决组件间交互问题。
### 方案1 原型链查找
要看被触发组件的时间是否写在prototype上面，可以参考mip-video代码（https://github.com/mipengine/mip/blob/master/src/components/mip-video.js ）和mip-video页面（http://m.jia.com/zixun/gfh/526459.html ），在页面控制台里面 document.querySelector('mip-video').customElement.renderInView 是能够调用video方法的

### 方案2 组件事件封装+trigger
![image](https://user-images.githubusercontent.com/8498677/37506550-4f16cb50-2925-11e8-8267-9ccb5d3b739d.png)
在主动触发的组件上，定义相应的事件并抛出。利用dom广播来触发另一个组件的事件。比如：<mip-check on="fail:video.renderInView"><mip-check>, 在组件中定义fail事件并trigger。这个还没有demo，尽快补充到文档。

另外，文档换个名字，别叫其他了。https://www.mipengine.org/doc/3-widget/6-help/3-mip-normal.html

**Comment by xuexb** [comment]
#228

**Comment by jennyliang220** [comment]
https://www.mipengine.org/doc/3-widget/6-help/3-mip-normal.html 已上线，问题close
