### ISSUE TITLE
我还是没看明白怎么改！

### ISSUE THREAD

**Issue by shenchengren** [mipengine/mip#290]
我现在有现成的wap页面，我要改成mip页面的话，我是在原网页改？还是我再写一个页面，然后连接啊？而且我用mip写完页面有什么具体效果啊？seo优化？还是别的用户浏览我的页面的时候，访问速度加快啊？访问速度加快的话，用户访问的是我的原页面还是mip页面？mip页面的话我的原页面还有存在的必要么？

**Comment by jennyliang220** [comment]
常见问题的答案详见[MIP 问题解决方案大全](https://github.com/mipengine/mip/wiki/MIP-%E9%97%AE%E9%A2%98%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E5%A4%A7%E5%85%A8)
