### ISSUE TITLE
使用rem布局，不使用自定义js代码如何计算根字体大小？

### ISSUE THREAD

**Issue by Nathanlee2010** [mipengine/mip#294]
> 警告出于对代码质量和性能的考虑，MIP 页中不允许自定义 JavaScript 代码。

规范不允许使用rem布局？

**Comment by littleColaer** [comment]
可以使用媒体查询结合rem

**Comment by VenyXiong** [comment]
可以自己封装mip-rem的组件哈~封装的组件里是可以去设置rem的基础值的
