### ISSUE TITLE
mip-nav-slidedown不支持PC端吗?

### ISSUE THREAD

**Issue by Caozao** [mipengine/mip#304]
mip-nav-slidedown组件在PC端下不能弹出，但是在手机端能正常弹出。

**Comment by VenyXiong** [comment]
『MIP（Mobile Instant Pages - 移动网页加速器），是一套应用于移动网页的开放性技术标准。』
目前我们并不对PC端浏览器组件的兼容性做保证，但是对于开发调试来说，正常chrome上的效果是OK的，可以具体提供下问题页面的链接么？

类似组件问题也可以咨询mip 组件哥。
MIP技术答疑QQ：2449408887 （MIP组件哥）
