### ISSUE TITLE
建议mip间页面跳转增加是否显示动画参数

### ISSUE THREAD

**Issue by KinoshitaHanson** [mipengine/mip#321]
<a data-type="mip"></a> 增加一个参数，开关过渡动画 ，有时候动画显得有些多余

**Comment by tayqassqan** [comment]
@oott123

**Comment by oott123** [comment]
`<a href="xxxx" data-type="mip" data-click="{&quot;anim&quot;:0}">链接</a>`

注意：就像上面的例子指出的，`data-click` 本身属性值为一个 json 字符串，如果你在 HTML 中使用，需要把其中的双引号 `"` 进行 HTML 实体编码，转义成 `&quot;`。

**Comment by KinoshitaHanson** [comment]
@oott123  请问需要额外引用什么js吗？我加了那个参数在mip预览中还是会有动画
