### ISSUE TITLE
请问下网站的逻辑代码，是不是也要弄成组件然后提交审核？

### ISSUE THREAD

**Issue by yxl720** [mipengine/mip#330]
请问下网站的逻辑代码，是不是也要弄成组件然后提交审核？这样是不是显得很麻烦

**Comment by xsteadybcgo** [comment]
同问，如果是，大量的js逻辑全部要改造，懵逼。

**Comment by VenyXiong** [comment]
是的，mip本身提供了很多现成的组件可以直接使用哈，详情可以查看https://www.mipengine.org/doc/3-widget/10-widgets.html。
