### ISSUE TITLE
mip-list  调接口报错 ，这是什么原因 怎么解决

### ISSUE THREAD

**Issue by MissQ7** [mipengine/mip#339]
mip-list 返回的数据要是jsonp的吗  有数据返回但我用{{name}}拿不到？

**Comment by allen886** [comment]
我也是 真坑  今天脑子都弄大了

**Comment by VenyXiong** [comment]
miplist返回的数据格式是需要jsonp。
详细问题可以联系mip 组件哥提供更详细的信息帮忙排查。
MIP技术答疑QQ：2449408887 （MIP组件哥）
