### ISSUE TITLE
提供从MIP-HTML转换成供MIP-Cache的新html/css的测试集合

### ISSUE THREAD

**Issue by fightmyway** [mipengine/mip#342]
**要解决什么问题**
mip-html经过检验后，会进行子资源路径替换生成供cache的新html，这个替换逻辑，不同引擎可能有不同的实验，替换的标准长期也可能会变更，需要有个公开的测试集合

**描述一下你理想中的解决方案**
清晰准确的描述你想怎么解决

**描述你的备选方案**
清晰准确的描述你考虑的备选方案

**补充信息**
补充其他信息，如截图等

**Comment by VenyXiong** [comment]
mipcatch改写规范可以查看这里哈https://www.mipengine.org/doc/2-tech/3-mip-cache.html
