### ISSUE TITLE
_proxyLink 可否用window.location而不是top.location?

### ISSUE THREAD

**Issue by LarryZhao0616** [mipengine/mip#344]
**要解决什么问题**
现在_proxyLink用的是top.location，如果需要在iframe内使用应用，跳转时会出现覆盖top的问题。

**描述一下你理想中的解决方案**
改用window.location

**描述你的备选方案**

**补充信息**
![mip111](https://user-images.githubusercontent.com/6835509/45615738-f7842880-ba9f-11e8-92e4-8bde130de5f6.png)

**Comment by VenyXiong** [comment]
mip页面在搜索被打开时，top域名是https的，当需要进行页面跳转时，我们采用top.location的形式是为了避免一些http域名的请求无法在https域下被加载的问题。
『如果需要在iframe内使用应用』这里具体的需求场景可以介绍下么？我们一起看下有没有更合适的方案来解决~

**Comment by LarryZhao0616** [comment]
ok了解了。
我们这边是一个第三方数据服务商，有一个业务功能是让客户在我们网站中的一个iframe内打开客户的网站，并让客户进行一些操作。
之前遇到的问题是我们的客户用了mip，因为top的问题，导致他们没法在我们网站内的iframe内完成一些操作（页面会直接跳转）。
目前我们的解决方案是开发了一款chorme插件，让客户在自己的网站进行操作。
（btw 我发现我们越来越多的客户在用mip呢。。）
