### ISSUE TITLE
mip-pix不支持Time Title Host替换

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip#84]
[mip-pix](https://www.mipengine.org/doc/3-widget/2-inner-widget/pix-widget.html)组件，https://m.a.com/js.gif?t={TIME}&title={TITLE}&host={HOST}&from=baidu ，请求不会替换“{}”的内容。

**Comment by ZE3kr** [comment]
目前我的测试是它会自动给 URL 添加 t、title、host 标签，但是不会替换 {} 的内容

**Comment by jennyliang220** [comment]
这个组件本周开始开发，主要修改点就是替换{}内容。请留一个使用了mip-pix的页面，做测试回归使用。

**Comment by ZE3kr** [comment]
[一个有 mip-pix 的页面](https://ssl.tloxygen.com/proxy.php/ze3kr.com/2016/08/self-host-dns/mip/)，现在是直接使用 PHP 打印出了文章标题和 URL 代替了 TITLE 和 HOST 的位置：

```html
<mip-pix src="https://ssl.ze3kr.com/piwik-gif.php?idsite=3&rec=1&action_name=%E8%87%AA%E5%BB%BA+PowerDNS+%E6%99%BA%E8%83%BD%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8+%26%238211%3B+ZE3kr&url=https%3A%2F%2Fze3kr.com%2F2016%2F08%2Fself-host-dns%2F"></mip-pix>
```

这个 amp-pix 实际发出的 GET 格式化后的请求是：

```
idsite	3
rec	1
action_name	自建 PowerDNS 智能解析服务器 &#8211; ZE3kr
urlref	
url	https://ze3kr.com/2016/08/self-host-dns/
t	1487211300738
title	自建 PowerDNS 智能解析服务器 – ZE3kr
host	https://ssl.tloxygen.com/proxy.php/ze3kr.com/2016/08/self-host-dns/mip/
```

虽然原本的 mip-pix 没有 t、title 和 host，却被自动加上了。此外，host 实际上不是 host，而是 URL。

还希望能够增加 REFERRER 变量，这样就能统计来源了，这也是统计中很重要的一个指标。[AMP 就支持这些变量](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md)

理想的 amp-pix 写法

```html
<mip-pix src="https://ssl.ze3kr.com/piwik-gif.php?idsite=3&rec=1&action_name={TITLE}&url={URL}&urlref={REFERRER}"></mip-pix>
```

**Comment by jennyliang220** [comment]
@ZE3kr mip-pix替换已经开发完成，可以到分支看效果：https://github.com/jennyliang220/mip/tree/mip-pix，文档：https://github.com/jennyliang220/mip/blob/mip-pix/src/components/mip-pix.md

**Comment by jennyliang220** [comment]
referrer添加办法也在文档中有说明，可以通过添加meta的方案解决
