### ISSUE TITLE
mip-video 不支持 source？

### ISSUE THREAD

**Issue by ZE3kr** [mipengine/mip#91]
根据[文档](https://www.mipengine.org/doc/3-widget/2-inner-widget/video-widget.html)，mip-video 可以支持 source 方式引入视频，但是经过实际测试，这样引入视频会出问题，视频根本无法正确加载（直接空白），浏览器报错：

```
TypeError: undefined is not an object (evaluating 'this.attributes.src.match')
firstInviewCallback — mip.js:4:9645
viewportCallback — mip.js:3:27496
setInViewport — mip.js:3:31962
_update — mip.js:4:107
_update
n — mip.js:2:29794
```

**Comment by ZE3kr** [comment]
HTML 内容大概是这样的：

```html
<mip-video class="……" width="525" height="295" poster="……" controls="" sizes="……">
	<source type="video/mp4" src="……"/>
	<source type="video/webm" src="……"/>
</mip-video>
```

**Comment by ZE3kr** [comment]
补充，在 [MIP 校验工具](https://www.mipengine.org/validator/validate)中，使用了 source 后会报错：
ERROR → line xxx,col 1: 标签'mip-video'的强制性属性'src'缺失

**Comment by pearlwang1106** [comment]
我们的校验升级开发完了，但是由于一些原因目前上线被delay了，目前正在推进这件事情，还请谅解
