### ISSUE TITLE
mip-pix功能修改，进入可视区域才发送统计需求

### ISSUE THREAD

**Issue by momofan** [mipengine/mip#99]
review 源码，发现 pix 的执行在页面是一上来就会发送统计请求，有违 pix 的简单统计的最初设计原则，申请将 pix 改成进入可视区域才执行，这样修改后，比如我想知道页面的某个模块（非首屏）用户看到了这样的统计需求，就很方便，只需在这个模块添加一个 mip-pix 即可。

**Comment by jennyliang220** [comment]
与 #103 一起上线。

**Comment by momofan** [comment]
已上线
